// <auto-generated />
using System;
using BloodCare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodCare.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BloodCare.Models.JadwalDonor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kuota")
                        .HasColumnType("int");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("JadwalDonors");
                });

            modelBuilder.Entity("BloodCare.Models.Pendonor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GolonganDarah")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoHP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rhesus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalDonorTerakhir")
                        .HasColumnType("datetime2");

                    b.Property<int>("Umur")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pendonors");
                });

            modelBuilder.Entity("BloodCare.Models.PermintaanDarah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GolonganDarah")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JumlahKebutuhan")
                        .HasColumnType("int");

                    b.Property<string>("NamaPasien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rhesus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RumahSakit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalPermintaan")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PermintaanDarahs");
                });

            modelBuilder.Entity("BloodCare.Models.StokDarah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GolonganDarah")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JumlahKantong")
                        .HasColumnType("int");

                    b.Property<string>("Rhesus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalKadaluarsa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TanggalMasuk")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StokDarahs");
                });
#pragma warning restore 612, 618
        }
    }
}
